"""
ادغام دیتابیس کاراکترها:
  uploads/characters.json  (۵۰۰ کاراکتر اصلی کاربر)
+ ۴۰ کاراکتر One Piece
+ ۱۰۰ کاراکتر جدید از انیمه‌های دیگر
=> pyfighter/data/characters.json  (۶۴۰ کاراکتر)

اجرا:  python tools/build_characters.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(os.path.dirname(ROOT), "uploads", "characters.json")
OUT_DIR = os.path.join(ROOT, "pyfighter", "data")
OUT = os.path.join(OUT_DIR, "characters.json")
OUT_ADD = os.path.join(OUT_DIR, "characters_additions.json")

COST = {"Rare": 250, "Epic": 400, "Legendary": 650, "Mythic": 1000}

# (name, anime, city, world, architecture, element, element_family, role, rarity,
#  hp, atk, def, spd, tech, build, sig_name, sig_desc, ultimate, unlock_level)
ONE_PIECE = [
 ("Monkey D. Luffy","One Piece","Thousand Sunny Deck","Grand Line","a lion-headed brig sloop with a sun-yellow figurehead, orange grove and a rooftop aquarium bar","Rubber","Might","Brawler","Mythic",92,93,80,84,52,70,"Gomu Gomu no Mi / Gear Fifth","stretching rubber body, Gear Second speed, Gear Fourth bounce-armor, Conqueror's Haki and the cartoon-physics Sun God Nika awakening","Gear Fifth: Bajrang Gun",1),
 ("Roronoa Zoro","One Piece","Wano Dojo of Three Blades","Wano","a shadowed dojo of hanging katana racks, a stone lantern garden and Enma's cursed shrine","Blade","Might","Bruiser","Mythic",88,95,84,70,58,66,"Santoryu / King of Hell","three-sword style with Conqueror's Haki coating; Ashura triple-image assault and Enma's chakra-draining edge","King of Hell: Three Sword Dragon Damnation",1),
 ("Nami","One Piece","Weatheria Sky Garden","Cocoyasi Village","a floating island of weather scientists, tangerine groves and copper storm-gauges","Lightning","Lightning","Controller","Legendary",58,72,50,74,92,64,"Clima-Tact / Zeus","weather manipulation with thunder clouds, mirage illusions and the storm-cloud homie Zeus","Zeus Breeze Tempo: Raiden Storm",1),
 ("Usopp","One Piece","Boin Archipelago Greenhouse","Syrup Village","a carnivorous-jungle sniper's nest of pop-green plants, slingshot towers and a giant beetle statue","Nature","Earth","Marksman","Epic",60,70,48,62,85,60,"Kabuto Slingshot / Pop Greens","long-range plant-seed ammunition: Devil bamboo spikes, Impact Wolf, and Observation Haki sniping","God Usopp: Meteor Impact Dial",1),
 ("Vinsmoke Sanji","One Piece","Baratie Floating Restaurant","East Blue","a fish-shaped ship-restaurant with brass kitchens, a rooftop grill and Zeff's peg-legged statue","Fire","Fire","Brawler","Legendary",78,86,72,88,66,60,"Black Leg / Diable Jambe","blazing kicks with Sky Walk aerial mobility, Germa exoskeleton toughness and Ifrit Jambe","Ifrit Jambe: Hell Memories",1),
 ("Tony Tony Chopper","One Piece","Drum Kingdom Castle Lab","Drum Island","a snow castle atop a drum-shaped peak, cherry blossom snow and Kureha's potion laboratory","Beast","Beast","Support","Epic",70,64,66,60,80,58,"Rumble Ball / Monster Point","seven transformation points from Brain to Heavy to a towering Monster Point, plus doctor's healing kit","Monster Point: Kokutei Rumble",1),
 ("Nico Robin","One Piece","Ohara Tree of Knowledge","West Blue","the hollow library-tree of Ohara with spiral staircases of banned poneglyph rubbings","Flower","Cosmic","Controller","Legendary",62,76,54,66,90,70,"Hana Hana no Mi / Demonio Fleur","sprouts limbs anywhere to bind and snap enemies, blooms giant arms and the black-winged Demonio Fleur","Demonio Fleur: Gran Jacuzzi Clutch",2),
 ("Franky","One Piece","Water 7 Shipyard Dock One","Water 7","a canal city of galleon docks, Franky House scrap towers and the Puffing Tom sea-train station","Steel","Tech","Guardian","Legendary",90,82,88,50,72,80,"Cyborg Body / General Franky","cola-powered cyborg with Franky Radical Beam, Coup de Vent air cannon and the General Franky mecha","General Franky: Franky Radical Beam",2),
 ("Brook","One Piece","Thriller Bark Ballroom","Florian Triangle","a haunted ghost-ship ballroom of cobwebbed chandeliers and a violin-shaped stage","Soul","Shadow","Assassin","Epic",56,74,44,86,70,54,"Yomi Yomi no Mi / Soul Solid","soul-chilling sword slashes, astral projection through walls and a freezing Soul King serenade","Soul King: Ekaki Uta Hitoyogiri",2),
 ("Jinbe","One Piece","Fish-Man Island Ryugu Palace","Fish-Man Island","a bubble-domed coral palace ten thousand meters undersea with karate dojos and shark stables","Water","Water","Guardian","Legendary",92,80,90,58,66,74,"Fish-Man Karate / Fish-Man Jujutsu","strikes water itself to hit through armor, spear-waves and the Vagabond Drill wave torrent","Fish-Man Karate: Buraikan Tidal Strike",2),
 ("Portgas D. Ace","One Piece","Spade Pirates' Flame Cove","Grand Line","a cove of ember-lit sails, a spade-branded galleon and a fire-fist cliff carving","Fire","Fire","Bombardier","Legendary",72,92,60,80,64,60,"Mera Mera no Mi","fire logia body immune to physical attacks, Fire Fist beams, Flame Pillars and the Dai Enkai Entei sun","Dai Enkai: Entei",3),
 ("Sabo","One Piece","Revolutionary Army Baltigo HQ","Baltigo","a white-stone desert fortress of revolutionary banners and Dragon's war table","Fire","Fire","Bruiser","Legendary",76,86,70,78,68,64,"Ryusoken / Mera Mera no Mi","Dragon Claw fist inherited from Dragon, now blazing with Ace's flames: Fire Fist and Dragon's Breath","Ryusoken: Hiken Dragon Claw",3),
 ("Trafalgar Law","One Piece","Polar Tang Submarine Bay","North Blue","a yellow submarine's operating theatre docked beneath Flevance's white lead ruins","Space","Cosmic","Tactician","Mythic",68,84,62,76,96,70,"Ope Ope no Mi / ROOM","spatial surgeon's Room: Shambles teleport, Mes heart extraction, Gamma Knife and the Awakened K-ROOM","Awakened: Puncture Wille",3),
 ("Eustass Kid","One Piece","Victoria Punk Scrapyard","South Blue","a rust-red scrapyard fortress of magnetized junk towers and a skull-goggled figurehead","Magnet","Tech","Berserker","Legendary",82,92,70,58,66,68,"Jiki Jiki no Mi / Punk Gibson","magnetizes metal into giant arms, Punk Rotten mechs and repels with Awakened Damned Punk","Damned Punk: Electromagnetic Cannon",3),
 ("Boa Hancock","One Piece","Amazon Lily Throne Hall","Kuja Island","a jungle-island palace of snake-carved pillars, warrior arenas and a throne of petrified suitors","Love","Mind","Controller","Legendary",64,84,60,82,74,62,"Mero Mero no Mi","turns lustful hearts to stone with Mero Mero Mellow, Slave Arrow and Pistol Kiss, plus Conqueror's Haki","Perfume Femur: Stone Kiss",4),
 ("Dracule Mihawk","One Piece","Kuraigana Castle","Kuraigana Island","a gloomy stone castle on a baboon-haunted island, a cross-shaped sword pedestal and a lone throne","Blade","Might","Warlord","Mythic",84,98,82,72,88,76,"Yoru / World's Strongest Swordsman","the black blade Yoru splits ships and icebergs; flawless Armament Haki and hawk-eyed observation","Kokuto Arahoshi: World Cleaving Slash",4),
 ("Shanks","One Piece","Red Force Flagship","Grand Line","a crimson-hulled flagship with a straw-hat cabin shrine and a mural of Roger's crew","Haki","Cosmic","Warlord","Mythic",90,97,86,84,88,80,"Conqueror's Haki Mastery","overwhelming Haoshoku that knocks out crowds, future-sight-blocking Observation and Gryphon's Divine Departure","Divine Departure: Kamusari",4),
 ("Edward Newgate (Whitebeard)","One Piece","Moby Dick Whale Deck","New World","a whale-headed flagship with sixteen division banners and the throne of the World's Strongest Man","Quake","Earth","Warlord","Mythic",98,99,84,50,68,88,"Gura Gura no Mi","cracks the air itself, tilts islands with quake bubbles and sinks fleets with the Kaishin tsunami","Gura Gura: Kaishin World Quake",5),
 ("Kaido","One Piece","Onigashima Skull Dome","Wano","a skull-shaped mountain fortress wreathed in flame clouds, sake vats and Beast Pirates' war drums","Dragon","Beast","Warlord","Mythic",99,98,96,56,62,86,"Uo Uo no Mi: Azure Dragon","the Strongest Creature: thunder bagua kanabo, Blast Breath, flame clouds and the Hybrid Drunk Oni form","Ragnaraku: Divine Thunder Blast",5),
 ("Charlotte Linlin (Big Mom)","One Piece","Whole Cake Chateau","Totto Land","a wedding-cake castle of candy towers, living homie furniture and the Tamatebako treasury","Soul","Shadow","Warlord","Mythic",98,96,94,52,80,84,"Soru Soru no Mi / Zeus, Prometheus, Napoleon","steals souls to animate homies; Ikoku Sovereignty shockwaves and the Misery lightning cannon","Maser Cannon: Misery Full Power",5),
 ("Marshall D. Teach (Blackbeard)","One Piece","Hachinosu Pirate Island","Fullalead","a skull-rock pirate haven of taverns, execution platforms and a dark treasury of stolen Devil Fruits","Dark","Shadow","Warlord","Mythic",96,94,80,58,84,78,"Yami Yami no Mi / Gura Gura no Mi","darkness that swallows and nullifies Devil Fruits, Black Hole vacuum, and the stolen quake power","Kurouzu: Twin Fruit Cataclysm",6),
 ("Donquixote Doflamingo","One Piece","Dressrosa Royal Palace","Dressrosa","a flamingo-pink palace atop a Colosseum city, toy-soldier barracks and a string-cage sky","String","Tech","Trickster","Mythic",80,90,74,86,88,72,"Ito Ito no Mi / Awakened Strings","razor strings that slice, puppet enemies with Parasite, Sky Path walking and the Bird Cage dome","Birdcage: God Thread",6),
 ("Sir Crocodile","One Piece","Rain Dinners Casino","Alabasta","a pyramid-shaped desert casino with crocodile pits, banana-gator moat and Baroque Works vaults","Sand","Earth","Tactician","Legendary",78,86,72,66,82,70,"Suna Suna no Mi","sand logia that desiccates by touch, Desert Spada blades, Sables sandstorm and the golden hook","Desert La Spada: Ground Death",6),
 ("Charlotte Katakuri","One Piece","Komugi Island Mochi Mill","Totto Land","a wheat-and-donut mill kingdom of mochi silos and a private tea tower for a scarfed noble","Mochi","Earth","Bruiser","Mythic",90,94,86,72,92,78,"Mochi Mochi no Mi / Future Sight","sees seconds ahead with Observation Haki; Mochi trident, Power Mochi fists and Zan Giri Mochi","Zan Giri Mochi: Future Sight Slash",7),
 ("Sakazuki (Akainu)","One Piece","Marineford New Headquarters","New World","a fortress of magma-red battlements, justice banners and a molten dog-head cannon gate","Magma","Fire","Warlord","Mythic",92,98,88,60,70,80,"Magu Magu no Mi","magma logia that burns even fire, Dai Funka fists, Ryusei Kazan meteor rain and Inugami Guren","Ryusei Kazan: Meteor Volcano",7),
 ("Kuzan (Aokiji)","One Piece","Frozen Sea Bicycle Bridge","Grand Line","an endless ice bridge across an ocean, an ice-sculpture garden and a lazy admiral's sleeping mask","Ice","Frost","Tactician","Legendary",84,88,80,64,86,72,"Hie Hie no Mi","ice logia that freezes oceans, Ice Time petrification, Ice Saber and the Ice Age tidal freeze","Ice Age: Frozen Ocean",7),
 ("Borsalino (Kizaru)","One Piece","Marine Light Cannon Spire","Marineford","a golden spire of mirrored lenses and a light-cannon that flashes across the archipelago","Light","Light","Marksman","Mythic",78,94,74,99,80,66,"Pika Pika no Mi","light-speed body, Yasakani no Magatama shard barrage, Ama no Murakumo light sword and light kicks","Yasakani no Magatama: Light Speed Kick",8),
 ("Monkey D. Garp","One Piece","Foosha Village Hero Hill","East Blue","a windmill-village hill with a cannonball-tossing training yard and a hero's stone fist","Haki","Might","Brawler","Mythic",94,96,88,66,64,78,"Fist of Love / Galaxy Impact","legendary Marine hero whose Haki-infused fists throw cannonballs and crater islands","Galaxy Impact: Fist of Love",8),
 ("Sengoku","One Piece","Marineford Buddha Terrace","Marineford","a golden terrace with a gilded Buddha statue, judge's gavel and a goat-tended garden","Holy","Light","Guardian","Legendary",88,86,90,54,90,80,"Hito Hito no Mi: Model Daibutsu","transforms into a golden Buddha whose palm strikes fire shockwaves; the Marines' master strategist","Daibutsu: Shockwave Palm",8),
 ("Enel","One Piece","Skypiea Shrine of Upper Yard","Skypiea","a cloud island temple of golden bells, Maxim ark and lightning-scarred pillars","Lightning","Lightning","Caster","Mythic",70,96,60,90,88,66,"Goro Goro no Mi","lightning logia with Mantra island-wide sensing, El Thor pillars and the Raigo thundercloud","Raigo: 200 Million Volt Amaru",9),
 ("Rob Lucci","One Piece","Enies Lobby Tower of Justice","Enies Lobby","a waterfall-ringed justice tower with locked gates, agent training halls and a leopard perch","Beast","Beast","Assassin","Legendary",78,90,74,90,72,66,"Rokushiki / Neko Neko no Mi: Leopard","Six Powers master: Shigan, Rankyaku, Soru, plus Awakened leopard form and the Rokuogan shockwave","Rokuogan: Awakened Leopard",9),
 ("Yamato","One Piece","Onigashima Ice Cavern","Wano","a frozen cavern beneath the skull dome with Oden's journal shrine and a chained kanabo pedestal","Ice","Frost","Bruiser","Legendary",86,88,80,74,64,70,"Inu Inu no Mi: Okuchi no Makami","the wolf-god fruit with Ice Fang breath, Conqueror's Haki-infused Thunder Bagua and Namuji Glacier Fang","Namuji Hyoga: Glacier Fang",9),
 ("Marco the Phoenix","One Piece","Sphinx Island Village","New World","a sphinx-guarded village of blue-flame lanterns, a phoenix roost and a doctor's clinic","Flame","Fire","Support","Legendary",86,80,84,80,84,70,"Tori Tori no Mi: Phoenix","blue regenerating flames heal self and allies, talon strikes and the Bluebird phoenix dive","Bluebird: Phoenix Brand",10),
 ("Silvers Rayleigh","One Piece","Sabaody Coating Workshop","Sabaody Archipelago","a bubble-tree archipelago workshop of coated hulls, a gambling den and the Roger Pirates' memorial","Haki","Cosmic","Tactician","Mythic",82,92,84,78,96,76,"Dark King's Haki Mastery","the Dark King: perfect Armament ryuo that repels from within, Conqueror's bursts and pinpoint swordplay","Dark King: Ryuo Internal Destruction",10),
 ("Gol D. Roger","One Piece","Laugh Tale Final Island","Laugh Tale","the last island of laughing stone monuments, an ancient treasure vault and the poneglyph of the century","Haki","Cosmic","Warlord","Mythic",94,99,88,80,84,82,"Pirate King's Divine Departure","the Pirate King with Haki that clashes skies apart; Ace's sword Divine Departure and Voice of All Things","Kamusari: Pirate King's Departure",10),
 ("Kozuki Oden","One Piece","Kuri Castle of Wano","Wano","a mountain castle over a lawless region, oden pots steaming and the two swords Enma and Ame no Habakiri","Blade","Might","Bruiser","Mythic",92,96,82,74,70,74,"Oden Two-Sword Style","Togen Totsuka: the only slash to ever scar Kaido, Paradise Totsuka and a boiling-oil endurance legend","Togen Totsuka: Paradise Slash",11),
 ("Smoker","One Piece","G-5 Marine Base","New World","a smog-shrouded Marine base of cigar-shaped chimneys, seastone jitte racks and a motorbike hangar","Smoke","Wind","Guardian","Epic",76,74,72,70,72,66,"Moku Moku no Mi","smoke logia capture with White Blow, White Snake and the seastone-tipped Nanashaku Jitte","White Launcher: Seastone Jitte",11),
 ("Bartholomew Kuma","One Piece","Sorbet Kingdom Chapel","Sorbet Kingdom","a snowy chapel of a gentle giant, paw-print pews and the Buccaneer memorial","Paw","Cosmic","Guardian","Legendary",94,82,92,60,76,84,"Nikyu Nikyu no Mi / Pacifista","paw pads that repel anything: Pad Ho pressure cannon, Ursus Shock and teleporting enemies across seas","Ursus Shock: Compressed Air Paw",11),
 ("Magellan","One Piece","Impel Down Level Six","Impel Down","an undersea prison of poison moats, wolf units and the warden's toilet-throne office","Poison","Blood","Controller","Legendary",84,88,86,48,80,72,"Doku Doku no Mi","poison hydra, Venom Demon Hell's Judgement and Kinjite's sea of death; a body of poison itself","Kinjite: Venom Demon Hell's Judgement",12),
 ("Issho (Fujitora)","One Piece","Marine Gravity Meditation Deck","Marineford","a blind admiral's stone garden of floating boulders, a meteor scar and a wooden sword rack","Gravity","Cosmic","Tactician","Legendary",84,90,84,60,88,74,"Zushi Zushi no Mi","gravity blade that pulls meteors from orbit, Gravito Moko crush and gravity dome protection","Moko Gyoku: Meteor Crash",12),
]

OTHERS = [
 # --- Cyberpunk: Edgerunners
 ("David Martinez","Cyberpunk: Edgerunners","Night City Megabuilding H4","Night City","a neon-scarred megabuilding of stacked apartments, chrome clinics and Arasaka billboards","Tech","Tech","Berserker","Legendary",80,88,66,90,54,66,"Sandevistan / Cyberpsychosis","military Sandevistan time-dilation slides, chrome fists and a cyberpsychotic rampage that ignores pain","Sandevistan Overdrive: Chrome Rampage",1),
 ("Lucy","Cyberpunk: Edgerunners","Moon-View Rooftop","Night City","a rooftop of holo-moon projections, netrunner chairs and a monowire hum","Mind","Mind","Assassin","Epic",56,80,44,84,90,52,"Monowire / Netrunning","razor-monowire slices and neural hacks that stun, blind and short enemy cyberware","Quickhack: Cyberware Meltdown",1),
 ("Rebecca","Cyberpunk: Edgerunners","Afterlife Bar Back Alley","Night City","a graffiti alley behind a merc bar with shotgun racks and a pink motorbike","Gun","Tech","Marksman","Epic",54,84,40,80,52,44,"Twin Shotguns / Reflex Boosts","tiny frame, giant Guts shotguns; leaps and blasts point-blank with mantis-fast reflexes","Guts Overkill: Shotgun Spin",1),
 ("Maine","Cyberpunk: Edgerunners","Edgerunner Garage","Night City","a scrap-garage of chrome limbs, a gilded helmet and ammo crates","Steel","Tech","Bruiser","Epic",88,82,80,52,50,74,"Full Chrome Body","heavy Gorilla Arms, subdermal armor and a cyberpsycho meltdown that flattens crews","Chrome Meltdown: Gorilla Slam",2),
 ("Adam Smasher","Cyberpunk: Edgerunners","Arasaka Tower Summit","Night City","a black corporate spire's rooftop of gunship pads and a full-borg trophy hall","Steel","Tech","Warlord","Mythic",98,96,98,60,58,90,"Full-Borg Chassis","armored borg juggernaut with arm cannons, Sandevistan counter and shoulder rockets","Sandevistan Slaughter: Rocket Barrage",2),
 # --- Made in Abyss
 ("Reg","Made in Abyss","Orth Cliff Town","Orth","a town clinging to the rim of a giant pit, bell-tower orphanage and relic warehouses","Beam","Tech","Marksman","Legendary",76,86,82,72,62,64,"Incinerator / Extending Arms","robot boy with grappling arms and the Incinerator beam that reshapes the abyss but knocks him out","Incinerator: Full Charge",2),
 ("Nanachi","Made in Abyss","Idofront Hideout","Abyss Layer 5","a nest of fluffy blankets, alchemical herb racks and a sea of blooming cradle flowers","Curse","Cosmic","Support","Epic",58,62,54,74,94,56,"Curse Sight / Field Medicine","sees the abyss's curse as flow, heals and guides allies, throws venom-tipped needles","Curse Sight: Force Field Guide",2),
 ("Riko","Made in Abyss","Belchero Orphanage","Orth","a bell-domed orphanage of cave-raider whistles, relic shelves and maps of the abyss","Physical","Might","Tactician","Rare",50,52,44,64,82,46,"Relic Toolkit / Blaze Reap","adventurer's arsenal: Blaze Reap pickaxe, Star Compass and a bottomless survival grit","Blaze Reap: Relic Strike",3),
 ("Bondrewd","Made in Abyss","Idofront Fortress","Abyss Layer 5","a stark research fortress of praying hands, cartridge tanks and Sparagmos altars","Curse","Cosmic","Warlord","Mythic",90,94,88,70,96,80,"Sparagmos / Zoaholic","the Sovereign of Dawn: cutting light relic Sparagmos, cartridge-fueled curse immunity and body-swap rebirth","Sparagmos: Blessing of Dawn",3),
 # --- Mushoku Tensei
 ("Rudeus Greyrat","Mushoku Tensei","Buena Village Manor","Asura Kingdom","a countryside manor of magic tutoring rooms, a cannon-shaped mana lab and a demon-eye workshop","Magic","Cosmic","Caster","Legendary",64,90,58,66,96,64,"Voiceless Incantation / Stone Cannon","chantless quick-cast water and earth magic, Demon Eye of Foresight, and the mud-cannon Stone Cannon","Cumulonimbus: Full Mana Storm",3),
 ("Eris Boreas Greyrat","Mushoku Tensei","Boreas Manor Sword Yard","Asura Kingdom","a red-lion noble manor with a sword-training yard, torn targets and a sword-king banner","Blade","Might","Berserker","Epic",74,90,54,82,40,50,"Sword God Style","light-fast Sword God strikes and a fury that turns every duel into an all-out charge","Sword God Style: Longsword of Light",3),
 ("Roxy Migurdia","Mushoku Tensei","Migurd Village Marsh","Demon Continent","a marsh village of blue-haired telepaths, mana tutor huts and a staff-topped teacher's tower","Water","Water","Caster","Epic",56,80,50,64,92,58,"Water Saint Magic","water and ice magic with Icicle Field, Water Fall and a saint's mastery of area spells","Water Saint: Icicle Field",4),
 ("Orsted","Mushoku Tensei","Dragon God Cave","Northern Territories","a hidden mountain cave of dragon runes, a loop-log library and a cursed white-haired god's throne","Dragon","Cosmic","Warlord","Mythic",98,98,92,82,98,86,"Dragon God's Loop Curse","master of all sword and magic styles across a hundred looping lives, with a curse that scares all","Dragon God: Secret Art Combo",4),
 # --- Devilman Crybaby
 ("Akira Fudo (Devilman)","Devilman Crybaby","Makimura Rooftop Track","Tokyo","a suburban rooftop of running tracks, a bloody moon and demon wings casting shadows","Demon","Blood","Berserker","Mythic",88,94,72,86,44,66,"Devilman Transformation","fused with Amon: winged demon speed, claws that shred, and a heart that keeps him human","Devil Wing: Amon Unleashed",4),
 ("Ryo Asuka (Satan)","Devilman Crybaby","Antarctic Fallen Throne","Earth's End","a white fallen-angel cathedral of ice, six wings of light and a ruined world","Holy","Light","Caster","Mythic",76,98,76,80,98,78,"Satan's Light","the fallen angel with beams of divine annihilation, hermaphroditic angel form and world-ending judgement","Satan's Judgement: Six-Winged Light",5),
 # --- Dorohedoro
 ("Caiman","Dorohedoro","Hole Gyoza Shop","Hole","a smog-choked slum of gyoza stalls, rusty magic doors and a bat-wielding lizard head","Physical","Might","Brawler","Legendary",90,84,84,62,48,70,"Lizard Head / Magic Immunity","bites sorcerers' heads to find the man inside; knife duel skills and immunity to magic","Head Bite: Inner Man's Verdict",5),
 ("Nikaido","Dorohedoro","Hungry Bug Restaurant","Hole","a tiny restaurant of steaming gyoza pans, boxing gloves and a time-magic seal","Time","Cosmic","Brawler","Legendary",74,84,66,84,72,60,"Time Magic / Martial Arts","brutal martial artist who bends time to rewind and rewrite a fight","Time Rewind: Devil Strike",5),
 ("En","Dorohedoro","En Family Mansion","Sorcerers' World","a mushroom-grown mansion of fungal towers, cross-eyed guards and a pie-shop cellar","Nature","Earth","Summoner","Legendary",78,86,72,52,90,74,"Mushroom Magic","turns anything into mushrooms, spawns fungal soldiers and giant spore explosions","Mushroom Kingdom: Spore Storm",6),
 ("Shin","Dorohedoro","Cleaners' Hammer Hall","Sorcerers' World","a butcher-like hall of heart-shaped masks, hammers on hooks and a bagged-head trophy wall","Blood","Blood","Assassin","Legendary",76,92,66,80,58,60,"Bisection Magic","cuts bodies into perfect slices with magic smoke and a hammer finishing blow","Hammer Time: Total Bisection",6),
 # --- Golden Kamuy
 ("Saichi Sugimoto","Golden Kamuy","Hokkaido Frozen Outpost","Hokkaido","a snow-bound army outpost of bayonet racks, bear hides and a gold-map campfire","Physical","Might","Bruiser","Legendary",90,82,78,66,52,62,"Immortal Sugimoto","a soldier who refuses to die: bayonet rushes, bear-wrestling grit and instant recovery","Immortal Charge: Bayonet Frenzy",6),
 ("Asirpa","Golden Kamuy","Ainu Kotan Village","Hokkaido","a riverside Ainu village of thatched cise homes, hunting bows and a smoked-fish kitchen","Nature","Earth","Marksman","Epic",52,68,46,72,92,50,"Poison Arrows / Ainu Hunting","surutku-poisoned arrows, animal traps and a hunter's knowledge of every terrain","Surutku Volley: Hunter's Snare",7),
 ("Hyakunosuke Ogata","Golden Kamuy","Abandoned Watchtower","Hokkaido","a frost-crusted hilltop tower with a sniper's blind and a lone cigarette glow","Gun","Tech","Marksman","Legendary",58,90,50,72,88,54,"Superior Private Sniper","emotionless dead-eye shooting through blizzards, unseen angles and cold ambushes","Sniper's Eye: Killing Shot",7),
 # --- Hell's Paradise
 ("Gabimaru the Hollow","Hell's Paradise","Iwagakure Village","Iwagakure","a stone ninja village of fire-forge caves, execution pits and a garden he built for his wife","Fire","Fire","Assassin","Legendary",74,90,68,92,66,60,"Ninpo: Ascetic Blaze","iron-hard body, ninpo fire techniques and Tao-enhanced blazing strikes","Ascetic Blaze: Ninpo Karyu",7),
 ("Yamada Asaemon Sagiri","Hell's Paradise","Yamada Clan Execution Grounds","Edo","a solemn execution yard of test-cutting posts, prayer rooms and a swordsmith's forge","Blade","Might","Tactician","Epic",60,80,56,76,86,54,"Executioner's Sword / Tao","flawless test-cutting draw-strikes, Tao sensing and breath-control counters","Tao Draw: Executioner's Cut",8),
 ("Yamada Asaemon Shion","Hell's Paradise","Blind Master's Dojo","Edo","a quiet dojo of wind-bells and a blind master's sensing garden","Spirit","Cosmic","Bruiser","Legendary",78,90,76,72,84,66,"Blind Tao Mastery","a blind executioner who reads Tao flows and cuts before seeing; incomparable defense","Tao Perfection: Void Cut",8),
 # --- Mashle
 ("Mash Burnedead","Mashle: Magic and Muscles","Easton Magic Academy Muscle Gym","Magic Realm","a wizard academy dormitory converted into a cream-puff bakery and a dumbbell gym","Physical","Might","Brawler","Legendary",90,94,84,74,30,66,"Pure Muscle","no magic, all muscle: punches that rip through spells, cream-puff-fueled toughness","Magic Muscle: Ten Thousand Punch",8),
 ("Lance Crown","Mashle: Magic and Muscles","Crown Gravity Dormitory","Magic Realm","a floating dormitory of gravity-anchored towers and a sister-portrait shrine","Gravity","Cosmic","Controller","Epic",62,80,58,70,90,60,"Gravity Magic: Gravioll","crushes and pins enemies with gravity fields, floats and slams debris","Gravioll Secondth: Absolute Crush",9),
 ("Rayne Ames","Mashle: Magic and Muscles","Divine Visionary Sword Hall","Magic Realm","a white-marble sword hall of floating blades and a stern brother's training square","Blade","Might","Assassin","Legendary",72,92,66,88,84,62,"Sword Magic: Sword Master","conjures a hundred flying swords and cuts with a divine visionary's speed","Sword Master Thirdth: Hundred Blade Storm",9),
 # --- Kaiju No. 8
 ("Kafka Hibino (Kaiju No. 8)","Kaiju No. 8","Defense Force Third Division HQ","Tachikawa","a hangar-fortress of kaiju-cleanup trucks, numbered-weapon vaults and an armored parade ground","Beast","Beast","Bruiser","Mythic",94,96,84,74,50,68,"Kaiju No. 8 Transformation","transforms into a humanoid kaiju with earth-shaking punches, regeneration and kaiju-sense","Kaiju No. 8: Full Release",9),
 ("Kikoru Shinomiya","Kaiju No. 8","Shinomiya Training Grounds","Tachikawa","a prestigious training ground of axe targets, elite barracks and a family crest gate","Physical","Might","Assassin","Legendary",70,88,62,92,72,58,"Numbered Weapon Axe / 96% Unleash","elite cadet with an oversized combat axe and near-perfect suit unleash for blur-fast strikes","Numbers 4 Axe: 96% Unleash",10),
 ("Mina Ashiro","Kaiju No. 8","Third Division Command Tower","Tachikawa","a command tower with a giant anti-kaiju cannon and a black-cat lounge","Gun","Tech","Marksman","Legendary",66,96,58,68,84,62,"Anti-Kaiju Long Cannon","one-shot kaiju killer whose long cannon obliterates anything downrange at 96% unleash","Long Cannon: 96% Kill Shot",10),
 ("Soshiro Hoshina","Kaiju No. 8","Hoshina Clan Blade Shrine","Tachikawa","a family dojo of anti-kaiju blades, cleaning rituals and a sarcastic vice-captain's tea corner","Blade","Might","Assassin","Legendary",72,92,64,94,78,60,"Hoshina-style Dual Blades","dual-blade combat of thousand-slash speed; the strongest close-range fighter in the force","Hoshina Style: Kaiju Cleaver Barrage",10),
 # --- Undead Unluck
 ("Andy","Undead Unluck","Union Roundtable Hall","Union HQ","a grand roundtable hall of artifact vaults, a regenerating man's bar and a bullet-hole ceiling","Blood","Blood","Bruiser","Mythic",99,88,86,78,60,68,"Undead","cannot die: uses blood as blades, bullets and jet propulsion; regenerates from anything","Undead: Fire Blood Bullet",11),
 ("Fuuko Izumo","Undead Unluck","Unluck Manor Rooftop","Nagasaki","a rooftop of a girl who brings bad luck, meteor-marks and a shojo manga shelf","Luck","Cosmic","Trickster","Legendary",60,78,54,72,92,58,"Unluck","anyone who touches her suffers catastrophic bad luck: falling planes, lightning and meteors","Unluck: Meteor Misfortune",11),
 # --- Dandadan
 ("Ken Takakura (Okarun)","Dandadan","Turbo Granny's Tunnel","Kanto","a cursed tunnel of racing lights, a shrine of stolen cursed objects and an occult club room","Speed","Shadow","Assassin","Legendary",70,86,62,98,58,58,"Turbo Granny's Curse","channels the curse: blistering speed, spectral tail swipes and hyper-mobility","Turbo Curse: Full Sprint Slam",11),
 ("Momo Ayase","Dandadan","Grandma Seiko's Shrine","Kanto","a spirit-medium's shrine house of ofuda talismans and psychic training hall","Psychic","Mind","Controller","Legendary",64,80,56,74,90,60,"Psychokinesis / Spirit Sight","telekinetic grabs, aura barriers and battle intuition against aliens and spirits alike","Psychokinetic Crush: Aura Burst",12),
 ("Turbo Granny","Dandadan","Cursed Speed Tunnel","Kanto","a haunted tunnel of blur-trails and a maneki-neko cat body shelf","Speed","Shadow","Trickster","Epic",56,80,50,99,72,46,"Cursed Velocity","a yokai of impossible speed and curses, later trapped in a lucky cat body but still fierce","Turbo Granny: Speed Curse Ram",12),
 # --- Wind Breaker
 ("Haruka Sakura","Wind Breaker","Furin High Rooftop","Makochi Town","a delinquent high school rooftop of shopping-street banners and a town that protects its own","Physical","Might","Brawler","Epic",76,82,66,80,46,56,"Bofurin Fist","raw street brawling with lightning-fast counters and a top-dog stubbornness","Furin Fist: Top of the Heap",12),
 ("Hajime Umemiya","Wind Breaker","Furin Rooftop Garden","Makochi Town","a rooftop vegetable garden of a gentle king, wooden benches and a view of Makochi","Physical","Might","Guardian","Legendary",92,88,88,66,60,70,"Leader of Bofurin","overwhelming strength restrained by kindness; single blows that end fights","Umemiya's Resolve: One Blow",13),
 # --- Sakamoto Days
 ("Taro Sakamoto","Sakamoto Days","Sakamoto Convenience Store","Tokyo","a family convenience store hiding a legendary hitman's arsenal in the snack aisle","Physical","Might","Tactician","Mythic",90,92,84,80,96,74,"Legendary Hitman Reflexes","turns anything into a weapon; slims down mid-fight for extreme speed and never kills","Slim Mode: Store Aisle Massacre",13),
 ("Shin Asakura","Sakamoto Days","Sakamoto Store Back Room","Tokyo","a stockroom of energy drinks, a sleeping bag and a psychic's training notepad","Psychic","Mind","Assassin","Epic",62,78,54,86,84,52,"Mind Reading Combat","reads opponents' thoughts a second ahead to dodge and counter perfectly","Clairvoyant Counter: Mind Blade",13),
 ("Nagumo","Sakamoto Days","Order Headquarters","Tokyo","a shadowy assassin's HQ of disguise closets, a knife wall and a joker's mirror","Illusion","Mind","Trickster","Legendary",70,88,62,88,90,60,"Master of Disguise / Knife","shape-shifting disguises, knife throws from impossible angles and a playful lethal edge","Nagumo's Trick: Face-Swap Kill",14),
 # --- Ranking of Kings
 ("Bojji","Ranking of Kings","Bosse Kingdom Great Hall","Bosse Kingdom","a giant-built castle with tiny-prince steps, a training yard and Kage's shadow corner","Physical","Might","Assassin","Legendary",50,86,44,96,88,44,"Despa's Sword Style","deaf, tiny prince who cannot cut, but strikes vital points with sword-tap precision and dodges everything","Prince's Resolve: Vital Point Storm",14),
 ("Kage","Ranking of Kings","Shadow Clan Ruins","Bosse Kingdom","a ruined assassin village of black-shadow pools and a prince's loyal friend's hideout","Shadow","Shadow","Trickster","Epic",54,72,52,80,80,46,"Shadow Clan Body","a living shadow that slips through cracks, steals and stabs from the dark","Shadow Dive: Backstab",14),
 ("Despa","Ranking of Kings","Underworld Training Hall","Underworld","a gaudy training hall of a vain master, magic mirrors and a fabulous cape rack","Magic","Cosmic","Support","Epic",52,60,48,60,94,56,"Master Swordsmanship Teacher","sees talent in anyone; buffs allies and casts sparkling counter-magic","Despa's Lesson: Sparkling Guidance",15),
 # --- The Eminence in Shadow
 ("Cid Kagenou (Shadow)","The Eminence in Shadow","Shadow Garden Hideout","Midgar Kingdom","a hidden mansion of black-cloaked elites, a slime-sword vault and a chuunibyou's throne","Shadow","Shadow","Assassin","Mythic",82,98,80,94,80,64,"Slime Sword / I Am Atomic","a trained-to-the-bone shadow lord with a shape-shifting slime blade and the world-erasing I Am Atomic","I Am Atomic",15),
 ("Alpha","The Eminence in Shadow","Shadow Garden Elf Sanctum","Midgar Kingdom","an elf sanctum of moonlit blades and the Seven Shadows' council table","Blade","Might","Assassin","Legendary",70,92,64,92,86,60,"Shadow Garden's First","elf swordswoman whose slime-blade dances rival Shadow himself","Alpha Style: Moonlit Requiem",15),
 # --- Samurai Champloo
 ("Mugen","Samurai Champloo","Ryukyu Pirate Cove","Ryukyu","a sun-bleached island cove of pirate shacks, breakdance circles and a bounty board","Blade","Might","Berserker","Legendary",74,90,60,90,50,56,"Champloo Kendo","unpredictable breakdance swordplay with metal geta kicks and street-fight dirty tricks","Champloo: Windmill Slash Frenzy",16),
 ("Jin","Samurai Champloo","Mujushin Dojo Ruins","Edo","a burned-down dojo of formal tatami, glasses on the altar and a killed master's sword","Blade","Might","Assassin","Legendary",68,92,64,86,80,58,"Mujushin Kenjutsu","flawless classical swordsmanship with a sacrificial final counter","Mujushin: Sacrifice Counter",16),
 # --- Afro Samurai / Ninja Scroll
 ("Afro Samurai","Afro Samurai","Number Two Headband Cliff","Feudal Future","a cliff of a fallen father's cross, headband billboards and Ninja Ninja's chatter","Blade","Might","Assassin","Legendary",76,94,66,88,62,60,"Number Two Headband","the Number Two who cuts through armies of headband hunters to face the god-like Number One","Number Two: Justice Cut",16),
 ("Jubei Kibagami","Ninja Scroll","Shimoda Ninja Village","Feudal Japan","a poisoned ninja village of rope bridges, demon forges and a wandering ronin's fire","Blade","Might","Bruiser","Legendary",76,90,70,84,64,62,"Vagabond Sword / Wind Slash","a vagabond who beats the Eight Devils of Kimon with a thrown sword-slash and sheer stubbornness","Kimon Slayer: Thrown Blade Return",17),
 # --- Claymore
 ("Clare","Claymore","Organization Training Grounds","Sutare","a grey stone fortress of half-yoma warriors, claymore racks and awakening-scarred yards","Blade","Blood","Assassin","Legendary",72,88,68,90,74,60,"Quicksword / Teresa's Flesh","Quicksword arm from Irene; Wind-Cutter speed and a yoki-suppressed body built on Teresa's blood","Quicksword: Awakened Wind Cutter",17),
 ("Teresa of the Faint Smile","Claymore","Teresa's Mountain Refuge","Sutare","a snow-mountain refuge with a broken claymore sign and a calm smile carved in stone","Blade","Blood","Warlord","Mythic",86,98,84,94,96,70,"Faint Smile Mastery","the strongest Claymore ever: reads yoki with zero release, cuts Priscilla-class foes with ease","Faint Smile: Perfect Read Slash",17),
 ("Priscilla","Claymore","Awakened Being Wasteland","North Lands","a devastated northern wasteland of single-horned shadows and shattered towns","Demon","Blood","Berserker","Mythic",94,99,84,90,50,74,"Awakened Being Priscilla","the one-horned Awakened Being with regeneration, extending limbs and unmatched yoki","Awakened Priscilla: Horn Impalement",18),
 # --- Soul Eater
 ("Maka Albarn","Soul Eater","Death Weapon Meister Academy","Death City","a skull-spired academy of laughing sun, candle-lit halls and weapon-partner dorms","Soul","Cosmic","Bruiser","Legendary",72,86,66,78,84,60,"Scythe Meister / Soul Perception","wields Soul the scythe, Witch Hunter slash and Genie Hunter anti-madness wavelength","Kishin Hunter: Soul Resonance",18),
 ("Death the Kid","Soul Eater","Gallows Mansion","Death City","a perfectly symmetrical mansion of twin pistols, Lines of Sanzu portraits and skull-motifs","Death","Shadow","Marksman","Legendary",68,88,64,80,90,62,"Death Cannon / Lines of Sanzu","twin pistol Liz & Patty, symmetrical soul-wavelength shots, Death Cannon and Beelzebub skateboard","Death Cannon: Three Lines of Sanzu",18),
 ("Black Star","Soul Eater","Star Clan Ruins","Death City","a dark assassin-clan ruin of star-marked stones and a very loud ego","Shadow","Shadow","Assassin","Epic",70,86,58,90,54,56,"Shadow Star / Soul Wavelength","assassin who can't stay quiet: Black Star Big Wave direct wavelength punches and Tsubaki weapon forms","Shadow Star: Uncanny Sword Mode",19),
 ("Franken Stein","Soul Eater","Stein's Patchwork Lab","Death City","a stitched laboratory of rolling chairs, dissection tables and a screw-through-head chalkboard","Soul","Cosmic","Tactician","Legendary",78,86,70,74,98,64,"Soul Thread Sutures / Soul Force","dissects anything; Soul Force wavelength strikes and sutures that pin opponents in place","Soul Thread: Total Dissection",19),
 # --- D.Gray-man / Noragami
 ("Allen Walker","D.Gray-man","Black Order Headquarters","Europe","a gothic tower HQ of exorcist gates, science division labs and the Ark's white city gate","Holy","Light","Bruiser","Legendary",74,88,70,80,80,64,"Crown Clown / Sword of Exorcism","parasitic Innocence arm, Crown Clown cloak and the Sword of Exorcism that purifies akuma","Crown Clown: Edge End",19),
 ("Yato","Noragami","Yato's Roadside Shrine","Tokyo","a tiny hand-built shrine of five-yen coins, a jersey-clad god and a delivery-god business card","Spirit","Cosmic","Assassin","Legendary",70,90,62,92,76,58,"Sekki / God of Calamity","the delivery god who cuts phantoms with Sekki and a boundary-slashing 'Rend'","Rend: Sekki Calamity Slash",20),
 ("Bishamonten","Noragami","Bishamon's Heavenly Estate","Takamagahara","a heavenly estate of a hundred shinki, a lion companion and a warrior god's armory","Holy","Light","Warlord","Mythic",84,94,86,80,82,76,"Vaisravana Arsenal","the war goddess wielding dozens of Regalias at once: guns, whips, blades and Kinuha shields","Vaisravana: Hundred Regalia Volley",20),
 # --- Akira / GitS / Psycho-Pass / Parasyte
 ("Shotaro Kaneda","Akira","Neo-Tokyo Highway Overpass","Neo-Tokyo","a neon-lit highway of bike gangs, riot police barricades and the Olympic stadium under construction","Tech","Tech","Marksman","Epic",64,76,56,84,66,54,"Laser Rifle / Red Bike","stolen military laser rifle and a red bike drift-kick; the gang leader who won't back down","Laser Rifle: Bike Drift Barrage",1),
 ("Tetsuo Shima","Akira","Olympic Stadium Crater","Neo-Tokyo","a shattered stadium of psychic craters, a floating throne and a red cape","Psychic","Mind","Caster","Mythic",76,98,78,72,88,70,"Awakened Psychic Power","telekinetic shockwaves, satellite-laser interception and a body that mutates into flesh","Akira Awakening: Psychic Singularity",2),
 ("Motoko Kusanagi","Ghost in the Shell","Section 9 Headquarters","New Port City","a high-tech police HQ of think-tanks, thermo-optic labs and a Major's rooftop dive spot","Tech","Tech","Tactician","Legendary",74,84,70,84,96,68,"Full Cyborg / Thermoptic Camouflage","optical-camo stealth, cyberbrain hacking and a prosthetic body with superhuman strength","Ghost Hack: Thermoptic Strike",3),
 ("Shinya Kogami","Psycho-Pass","MWPSB Division One","Tokyo","a sterile bureau of Dominator racks, Sibyl scans and an enforcer's smoking bench","Gun","Tech","Marksman","Epic",70,80,60,78,84,60,"Dominator / Detective Instinct","Sibyl-linked Dominator that paralyzes or eliminates, plus brutal boxing and detective intuition","Dominator: Lethal Eliminator",4),
 ("Shogo Makishima","Psycho-Pass","Makishima's Reading Room","Tokyo","a hidden library of banned books, a razor collection and a white-haired philosopher's lounge","Mind","Mind","Trickster","Legendary",64,84,56,84,98,62,"Criminally Asymptomatic","invisible to Sibyl scans; razor combat and psychological traps that turn allies against each other","Asymptomatic: Razor Philosophy",5),
 ("Shinichi Izumi / Migi","Parasyte","Izumi Residence","Tokyo","a quiet suburban home with a parasite-shaped garden statue and a right hand that eats lunch","Beast","Beast","Bruiser","Legendary",76,88,68,86,80,60,"Migi Parasite","right hand becomes blades and shields; enhanced body from a parasite's cells","Migi Fusion: Blade Storm",6),
 # --- Kingdom / Magi
 ("Shin (Li Xin)","Kingdom","Hi Shin Unit Camp","Qin","a war-camp of a rising general's banners, a spear rack of Ouki's glaive and a hill of ambitions","Physical","Might","Brawler","Legendary",84,90,72,80,58,64,"Ouki's Glaive","a servant boy turned general whose glaive strokes grow heavier with every fallen enemy","Great General's Slash: Ouki's Legacy",7),
 ("Ouki","Kingdom","Ouki's Great General Hall","Qin","a magnificent general's estate of bronze war drums, a giant glaive rack and a hearty laugh","Physical","Might","Warlord","Mythic",96,98,90,72,90,82,"Monstrous Bird of Qin","legendary Great General with bone-crushing glaive swings and instinctive battlefield command","Monstrous Bird: Battlefield Sovereign",8),
 ("Kyoukai","Kingdom","Shiyuu Clan Shrine","Qin","a mountain shrine of dance-sword rituals and a sister's grave","Blade","Might","Assassin","Legendary",64,94,60,96,82,54,"Shiyuu Priestess Dance","the Priestess Dance trance that multiplies speed; whirling sword kills before the eye can follow","Priestess Dance: Shiyuu Trance",9),
 ("Aladdin","Magi: The Labyrinth of Magic","Sindria Magic Tower","Sindria","a coral-white tower of a magi's flute, rukh light and a djinn's lounge","Magic","Cosmic","Caster","Legendary",62,88,58,72,98,66,"Magi / Solomon's Wisdom","commands rukh: Har-Har Infigar fireballs, magic barriers and Ugo's giant djinn arms","Solomon's Wisdom: Ugo Djinn Strike",10),
 ("Alibaba Saluja","Magi: The Labyrinth of Magic","Balbadd Palace Docks","Balbadd","a merchant kingdom of harbor palaces, Amon's flame-forge and a slums memorial","Fire","Fire","Bruiser","Legendary",74,88,70,82,72,62,"Amon Djinn Equip","Amon's flaming sword, Djinn Equip full body armor and Amol Saiqa heat wave","Amol Saiqa: Djinn Equip Blaze",11),
 ("Sinbad","Magi: The Labyrinth of Magic","Sindria Royal Palace","Sindria","an island kingdom palace of seven djinn shrines, tropical feasts and a high king's throne","Lightning","Lightning","Warlord","Mythic",88,96,84,82,94,84,"Seven Djinn Equips","the High King who equips Baal, Focalor and Zepar: lightning blade, wind and mind-control roar","Bararaq Saiqa: Seven Djinn Storm",12),
 # --- Dororo / Beastars / Goblin Slayer / Shield Hero / Franxx
 ("Hyakkimaru","Dororo","Hall of Hell Temple","Sengoku Japan","a ruined temple of twelve demon statues, a prosthetic-arm workshop and a road of returned limbs","Blade","Might","Assassin","Legendary",76,92,64,90,72,56,"Prosthetic Blade Arms","demon-hunting boy with swords hidden in prosthetic arms, sensing souls without sight","Demon Slaying: Twin Arm Blades",13),
 ("Legoshi","Beastars","Cherryton Academy Drama Club","Cherryton","a boarding school of carnivore/herbivore dorms, a backstage of props and a moonlit rooftop","Beast","Beast","Bruiser","Epic",78,84,70,78,60,58,"Grey Wolf Instinct","a gentle wolf whose fangs and speed surge when protecting someone","Wolf Instinct: Full Moon Fang",14),
 ("Goblin Slayer","Goblin Slayer","Frontier Adventurers Guild","Frontier","a bustling guild hall of quest boards, a farm outside town and a cave-mouth of torches","Physical","Might","Tactician","Epic",74,76,84,60,92,66,"Goblin Extermination Tactics","dirty tactics: torches, throwing knives, shield bashes and a sword just long enough","Goblin Slayer: Cave Purge",15),
 ("Naofumi Iwatani","The Rising of the Shield Hero","Raphtalia's Village Rebuilt","Melromarc","a rebuilt seaside village of the Shield Hero's merchant carts, a slave-crest shrine and a raccoon totem","Curse","Shadow","Guardian","Legendary",96,60,98,56,84,80,"Legendary Shield / Wrath Shield","unbreakable shields, Air Strike Shield walls and the cursed flames of the Wrath Shield","Wrath Shield: Iron Maiden",16),
 ("Zero Two","Darling in the Franxx","Plantation 13 Mistilteinn","Plantation 13","a greenhouse-dome birdcage city of pilot dorms and Strelizia's hangar","Beast","Beast","Berserker","Legendary",76,92,64,90,62,58,"Klaxosaur Blood / Strelizia","horned klaxosaur-hybrid with feral claws, and the Strelizia mecha's lance charge","Strelizia: Stampede Mode",17),
 # --- Durarara!!
 ("Shizuo Heiwajima","Durarara!!","Ikebukuro Vending Machine Street","Ikebukuro","a busy street of thrown vending machines, uprooted signs and a bartender's outfit shop","Physical","Might","Berserker","Mythic",92,98,80,72,36,68,"Ikebukuro's Strongest","inhuman anger-fueled strength: throws vending machines, guardrails and people","Vending Machine Rage: Guardrail Swing",18),
 ("Izaya Orihara","Durarara!!","Shinjuku Information Office","Shinjuku","a high-rise info-broker office of chessboards, phone banks and a knife drawer","Mind","Mind","Trickster","Legendary",56,80,50,90,98,56,"Information Broker / Flick Knife","parkour knife fighter who manipulates everyone into fighting for him","Human Chess: Knife Manipulation",19),
 ("Celty Sturluson","Durarara!!","Dullahan's Shadow Garage","Ikebukuro","a garage of a headless rider's black bike, shadow scythes and a helmet with cat ears","Shadow","Shadow","Controller","Legendary",78,84,74,86,72,62,"Dullahan Shadow","the headless rider forms scythes, nets and armor from living shadow; rides Shooter the horse-bike","Shadow Scythe: Dullahan's Ride",20),
 # --- Katekyo Hitman Reborn!
 ("Tsunayoshi Sawada","Katekyo Hitman Reborn!","Vongola Namimori Base","Namimori","a suburban house hiding a mafia base of dying-will flame lamps and a tutor's espresso bar","Fire","Fire","Bruiser","Legendary",74,88,70,84,70,60,"Dying Will / X-Burner","Hyper Dying Will mode with sky flames, X-Gloves flight and the X-Burner beam","X-Burner: Full Sky Flame",1),
 ("Kyoya Hibari","Katekyo Hitman Reborn!","Namimori Disciplinary Committee Room","Namimori","a school reception room of tonfa racks, a bird named Hibird and a cloud-flame hedgehog","Physical","Might","Assassin","Legendary",76,90,70,86,64,58,"Cloud Tonfa / Roll","tonfa strikes multiplied by cloud flames; propagating hedgehog Roll cages","Cloud Propagation: Tonfa Cage",2),
 ("Xanxus","Katekyo Hitman Reborn!","Varia Headquarters","Italy","a dark Italian castle of the assassination squad with flame-scorched throne and wrath","Fire","Fire","Marksman","Legendary",80,94,72,70,66,66,"Flame of Wrath Guns","dual flame pistols of Wrath that blast apart walls; Bester the liger box weapon","Colpo d'Addio: Flame of Wrath",3),
 # --- Bungo Stray Dogs
 ("Osamu Dazai","Bungo Stray Dogs","Armed Detective Agency Office","Yokohama","a harbor city office of detective desks, bandaged mysteries and a river for suicide attempts","Mind","Mind","Tactician","Legendary",62,70,56,80,99,62,"No Longer Human","nullifies any ability on touch; strategist who wins fights before they start","No Longer Human: Ability Nullification",4),
 ("Atsushi Nakajima","Bungo Stray Dogs","Yokohama Harbor Rooftops","Yokohama","port rooftops of a white tiger's leap, orphanage memories and detective agency rain","Beast","Beast","Bruiser","Legendary",82,88,72,88,54,60,"Beast Beneath the Moonlight","transforms into a white tiger with claws that shred and regeneration that heals lost limbs","Moonlight Tiger: Full Beast",5),
 ("Ryunosuke Akutagawa","Bungo Stray Dogs","Port Mafia Docks","Yokohama","fog-choked mafia docks of black coats, cargo shadows and a Rashomon warehouse","Shadow","Shadow","Assassin","Legendary",64,94,60,84,70,54,"Rashomon","the black-beast coat that devours space itself: Rashomon fangs, shields and Demonic Armor","Rashomon: Murakumo Devouring Fang",6),
 ("Chuuya Nakahara","Bungo Stray Dogs","Port Mafia Executive Suite","Yokohama","a mafia executive's suite of gravity-cracked walls, hat stands and a wine cellar","Gravity","Cosmic","Bruiser","Mythic",80,96,74,90,66,60,"Upon the Tainted Sorrow / Corruption","gravity manipulation with crushing kicks; Corruption unleashes black gravity spheres","Corruption: Tainted Sorrow Overdrive",7),
 # --- Toriko
 ("Toriko","Toriko","Gourmet Age Kitchen Camp","Human World","a wilderness camp of giant grills, ingredient cages and a bishokuya's tent","Physical","Might","Brawler","Mythic",96,96,82,72,54,78,"Fork, Knife & Nail Punch","Gourmet Cells: Fork thrusts, Knife slashes, multi-hit Nail Punch and appetite demon awakening","Appetite Demon: 100-Ren Nail Punch",8),
 ("Zebra","Toriko","Honey Prison Underground Pit","Human World","a maximum-security gourmet prison of sound-echo pits and a chained beast's cell","Sound","Wind","Bombardier","Mythic",98,98,84,60,60,80,"Sound Bazooka / Voice Missile","annihilates by voice: Sound Bazooka, Thunder Noise and Death Noise that stops hearts","Death Noise: Sound Armor Finale",9),
 # --- Black Lagoon
 ("Revy","Black Lagoon","Roanapur Yellow Flag Bar","Roanapur","a lawless Thai port city of a bullet-scarred bar, a torpedo boat dock and cigarette smoke","Gun","Tech","Marksman","Legendary",64,90,54,90,72,52,"Two Hands / Cutlass Berettas","dual custom Berettas fired in a dance of dodges and headshots; a killer who enjoys the job","Two Hands: Whirlwind Bullets",10),
 ("Roberta","Black Lagoon","Lovelace Family Estate","Venezuela","a colonial estate of a maid's umbrella gun, a ruined plantation and a sunset of vengeance","Gun","Tech","Berserker","Legendary",86,92,80,78,62,66,"Bloodhound of Florencia","a maid with an umbrella shotgun, unfeeling combat-drug frenzy and terminator durability","Bloodhound: Umbrella Massacre",11),
 # --- Delicious in Dungeon
 ("Laios Touden","Delicious in Dungeon","Golden Kingdom Dungeon Gate","Island Kingdom","a dungeon-town entrance of adventurer stalls, monster butcheries and a golden ruin below","Beast","Beast","Bruiser","Epic",78,82,70,66,70,64,"Monster Knowledge / Kensuke","monster-obsessed knight with a living sword Kensuke and beastly transformation instincts","Beast Form: Monster Lord Bite",12),
 ("Marcille Donato","Delicious in Dungeon","Dungeon Mage Laboratory","Island Kingdom","an underground lab of spell scrolls, a mandrake garden and a dark-magic staff stand","Magic","Cosmic","Caster","Legendary",56,86,48,64,96,58,"Ancient Magic / Lord of the Dungeon","elf mage with explosive elemental spells, healing and forbidden ancient magic that warps the dungeon","Dungeon Lord: Ancient Magic Surge",13),
 ("Senshi","Delicious in Dungeon","Dwarven Kitchen Camp","Dungeon Floor 3","a dwarven camp of a cooking pot on an adamantine axe and monster-cutting boards","Physical","Might","Guardian","Epic",88,74,88,50,72,74,"Adamantine Axe & Cookpot","dwarven cook whose adamant axe splits golems and whose pot shields allies","Adamantine Cleave: Cookpot Guard",14),
 # --- The God of High School
 ("Jin Mori","The God of High School","GOH Arena Seoul","Seoul","a stadium arena of national taekwondo banners, a Monkey King's cloud and a nyoibo rack","Physical","Might","Brawler","Mythic",90,96,78,92,60,64,"Renewal Taekwondo / Monkey King","Renewal Taekwondo kicks, Blue Dragon Kick and the Monkey King charyeok with the Ruyi Jingu staff","Monkey King: Nyoibo Descent",15),
 ("Han Daewi","The God of High School","Busan Boxing Gym","Busan","a seaside boxing gym of taped fists, a Haetae statue and a friend's hospital photo","Physical","Might","Bruiser","Legendary",82,88,78,80,66,64,"Full Contact Karate / Haetae","full-contact karate with the Haetae borrowed power: lightning fists and wind-splitting Wave","Haetae: Thunder Wave Fist",16),
 ("Yoo Mira","The God of High School","Moonlight Sword Dojo","Seoul","a family dojo of the Moon Light Sword Style, a moonlit yard and a sword under glass","Blade","Might","Assassin","Epic",68,84,60,84,74,54,"Moon Light Sword Style","the 25th master of Moon Light Sword: swift slashes and the charyeok Lu Bu's halberd","Moonlight: Lu Bu's Halberd",17),
 # --- Noblesse
 ("Cadis Etrama Di Raizel","Noblesse","Frankenstein's Mansion","Seoul","a stately mansion of a sleeping noble's coffin, a butler's lab and a ramen cupboard","Blood","Blood","Warlord","Mythic",86,99,84,88,90,74,"Blood Field / Noblesse Judgement","the Noblesse whose blood-red field erases anything; power that consumes his own life","Blood Field: Judgement of the Noblesse",18),
 ("Frankenstein","Noblesse","Ye Ran High School Principal's Office","Seoul","a school principal's office hiding a dark spear laboratory and a devoted butler's tea set","Dark","Shadow","Bruiser","Legendary",84,92,80,84,90,70,"Dark Spear","the Dark Spear weapon of consumed souls that he barely controls; a butler-scientist warrior","Dark Spear: Soul Devouring Storm",19),
]


def make(entry, new_id):
    (name, anime, city, world, arch, element, fam, role, rarity,
     hp, atk, df, spd, tech, build, sig, desc, ult, lvl) = entry
    power = round((hp + atk + df + spd + tech + build) / 6)
    return {
        "id": new_id,
        "name": name,
        "anime": anime,
        "city": city,
        "world": world,
        "architecture": arch,
        "element": element,
        "element_family": fam,
        "role": role,
        "rarity": rarity,
        "stats": {"hp": hp, "atk": atk, "def": df, "spd": spd,
                  "tech": tech, "build": build, "power_level": power},
        "signature": {"name": sig, "description": desc, "ultimate": ult},
        "brick_cost": COST[rarity],
        "city_pieces": 400 + build * 12,
        "unlock_level": lvl,
    }


def main():
    with open(SRC, encoding="utf-8") as f:
        base = json.load(f)
    next_id = max(c["id"] for c in base) + 1
    additions = []
    for e in ONE_PIECE + OTHERS:
        additions.append(make(e, next_id))
        next_id += 1

    names = [c["name"] for c in base + additions]
    assert len(names) == len(set(names)), "duplicate character names"

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_ADD, "w", encoding="utf-8") as f:
        json.dump(additions, f, indent=2, ensure_ascii=False)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(base + additions, f, indent=2, ensure_ascii=False)

    print(f"base={len(base)}  one_piece={len(ONE_PIECE)}  others={len(OTHERS)}  total={len(base)+len(additions)}")
    print("written:", OUT)


if __name__ == "__main__":
    main()
